<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Browser launch Successfully]]>
    </line>
    <line>
      <![CDATA[Login as Bank Manager]]>
    </line>
    <line>
      <![CDATA[Capturing screenshot for failure]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_06_IST_2019>Click to see Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_06_IST_2019><img src=Thu_Jul_18_16_52_06_IST_2019 height=200 widht=200 ></img></a>]]>
    </line>
    <line>
      <![CDATA[Capturing screenshot for failure]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_09_IST_2019>Click to see Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_09_IST_2019><img src=Thu_Jul_18_16_52_09_IST_2019 height=200 widht=200 ></img></a>]]>
    </line>
    <line>
      <![CDATA[Capturing screenshot for failure]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_11_IST_2019>Click to see Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_11_IST_2019><img src=Thu_Jul_18_16_52_11_IST_2019 height=200 widht=200 ></img></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2019-07-18T11:22:03Z" name="Banking" finished-at="2019-07-18T11:22:12Z" duration-ms="8644">
    <groups>
    </groups>
    <test started-at="2019-07-18T11:22:03Z" name="Bank Manager Login" finished-at="2019-07-18T11:22:04Z" duration-ms="521">
      <class name="com.w2a.testcases.BankManagerLogin">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLogin@50b5ac82]" started-at="2019-07-18T11:22:03Z" name="loginAsBankManager" finished-at="2019-07-18T11:22:04Z" duration-ms="506" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login as Bank Manager]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLogin -->
    </test> <!-- Bank Manager Login -->
    <test started-at="2019-07-18T11:22:04Z" name="Add Customer" finished-at="2019-07-18T11:22:12Z" duration-ms="8089">
      <class name="com.w2a.testcases.AddCustomer">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomer@4d465b11]" started-at="2019-07-18T11:21:58Z" name="setUp" finished-at="2019-07-18T11:22:03Z" duration-ms="5383" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser launch Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addcustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomer@4d465b11]" started-at="2019-07-18T11:22:04Z" name="addcustomer" data-provider="getData" finished-at="2019-07-18T11:22:06Z" duration-ms="2401" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Amir]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sikandar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[JSR]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomer.addcustomer(AddCustomer.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot for failure]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_06_IST_2019>Click to see Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_06_IST_2019><img src=Thu_Jul_18_16_52_06_IST_2019 height=200 widht=200 ></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addcustomer -->
        <test-method signature="addcustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomer@4d465b11]" started-at="2019-07-18T11:22:06Z" name="addcustomer" data-provider="getData" finished-at="2019-07-18T11:22:09Z" duration-ms="2283" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Darshan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Bora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[JSR]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomer.addcustomer(AddCustomer.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot for failure]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_09_IST_2019>Click to see Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_09_IST_2019><img src=Thu_Jul_18_16_52_09_IST_2019 height=200 widht=200 ></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addcustomer -->
        <test-method signature="addcustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomer@4d465b11]" started-at="2019-07-18T11:22:09Z" name="addcustomer" data-provider="getData" finished-at="2019-07-18T11:22:11Z" duration-ms="2228" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sanket]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Agrawal]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[JSR]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.testcases.AddCustomer.addcustomer(AddCustomer.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot for failure]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_11_IST_2019>Click to see Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Jul_18_16_52_11_IST_2019><img src=Thu_Jul_18_16_52_11_IST_2019 height=200 widht=200 ></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addcustomer -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.w2a.testcases.AddCustomer@4d465b11]" started-at="2019-07-18T11:22:12Z" name="teardown" finished-at="2019-07-18T11:22:12Z" duration-ms="605" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.w2a.testcases.AddCustomer -->
    </test> <!-- Add Customer -->
  </suite> <!-- Banking -->
</testng-results>
